#### Cleaning Invoice table and creating new one. Several products have the descriptions  misspelled

In [28]:
import pandas as pd
import numpy as np
import locale
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Define Moeda Brasileira numeros R$ 1.000,00
#locale.setlocale( locale.LC_ALL, '' )
#locale.currency( g, grouping = True )

In [29]:
from numpy.random import randn
#np.random.seed(101)

#### Opens the dataset with all the invoices imported from the XML files

In [30]:

# Forço o tipo das Colunas COD, NF e CNPJ como String se não abrem como Numérico
df = pd.read_csv('C:/Mettricx/Projetos/SFoods/DataSet/NFe-SupraAlimentos.csv', dtype={'cod': object, 'NF': object, 'CNPJ': object})

In [31]:
# Exclui a primeira coluna uma vez q tem erros de digitação. 
df.drop('descricao',axis=1,inplace=True)

In [32]:
# Tipo das Columas
df.dtypes

cliente     object
NF          object
data        object
CNPJ        object
cidade      object
bairro      object
UF          object
cod         object
QTY          int64
unidade     object
preco      float64
dtype: object

In [33]:
df.head(10)

,cliente,NF,data,CNPJ,cidade,bairro,UF,cod,QTY,unidade,preco
0,NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM ...,4,2014-08-29,27833615002018,RIO DE JANEIRO,CASIMIRO DE ABREU,RJ,020002,1,UN,2.77
1,NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM ...,5,2014-08-29,09309021000168,RIO DE JANEIRO,VILA NOVA DE CAMPOS,RJ,010002,1,UN,1.11
2,NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM ...,6,2014-08-29,09309021000168,ANGRA DOS REIS,VILA NOVA DE CAMPOS,RJ,010001,12,UN,9.72
3,NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM ...,6,2014-08-29,09309021000168,ANGRA DOS REIS,VILA NOVA DE CAMPOS,RJ,010002,1,UN,1.11
4,NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM ...,6,2014-08-29,09309021000168,ANGRA DOS REIS,VILA NOVA DE CAMPOS,RJ,010009,1,UN,1.43
5,NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM ...,6,2014-08-29,09309021000168,ANGRA DOS REIS,VILA NOVA DE CAMPOS,RJ,010010,1,UN,1.55
6,NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM ...,6,2014-08-29,09309021000168,ANGRA DOS REIS,VILA NOVA DE CAMPOS,RJ,010007,1,UN,1.43
7,NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM ...,7,2014-08-29,09309021000168,APERIBE,VILA NOVA DE CAMPOS,RJ,010010,1,UN,1.39
8,NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM ...,8,2014-08-29,09309021000168,ANGRA DOS REIS,VILA NOVA DE CAMPOS,RJ,010010,1,UN,1.39
9,NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM ...,9,2014-08-29,09309021000168,ANGRA DOS REIS,VILA NOVA DE CAMPOS,RJ,030003,1,UN,1.78

###### Products

#### TYype of Product (Family)

In [34]:

def famProdutos(xCod):
    x = str(xCod)
    yCod = x[:2]
    if yCod == '01':
        return 'Blister'
    elif yCod =='02':
        return 'Temperos'
    elif yCod =='03':
        return 'Molhos'
    elif yCod == '04':
        return 'Conservas'
    elif yCod =='05': 
        return 'Institucional'
    elif yCod == '06':
        return 'Diversos '
    elif yCod =='07':
        return 'Insumos'
    elif yCod =='08':
        return 'Consumo'
    elif yCod == '09':
        return 'Produtos Prontos para Venda'
    elif yCod =='10':
        return 'Serviço'
    elif yCod == '11':
        return 'Embalagens'
    elif yCod =='12':
        return 'Contas Fixas'
    elif yCod == '13':
        return 'Bem Ativo'
    elif yCod =='14':
        return 'Manutenção de Ativo'
    elif yCod =='15':
        return 'Display'
    elif yCod == '16':
        return 'Supra Life'

###### Load Products dataset

In [35]:
products = pd.read_csv('C:/Mettricx/Projetos/SFoods/DataSet/supraProdutos.csv', dtype={'cod': object, 'descricao': object}, encoding='latin-1')

In [36]:
products.head()

      cod unidade                                descricao
0  020002      UN    ALHO E CEBOLA  PICADINHO S/SAL  180GR
1  010002      UN                             ALECRIM 15GR
2  010001      UN                             ACAFRAO 15GR
3  010009      UN    CALDO DE CARNE  COM ERVAS FINAS  60GR
4  010010      UN  CALDO DE  GALINHA COM  ERVAS FINAS 60GR

#### Add product family name

In [37]:

products['Familia'] = products['cod'].apply(famProdutos)

In [40]:
products.head()

      cod                                descricao   Familia
0  020002    ALHO E CEBOLA  PICADINHO S/SAL  180GR  Temperos
1  010002                             ALECRIM 15GR   Blister
2  010001                             ACAFRAO 15GR   Blister
3  010009    CALDO DE CARNE  COM ERVAS FINAS  60GR   Blister
4  010010  CALDO DE  GALINHA COM  ERVAS FINAS 60GR   Blister

####  Merge the Two DataSets (Products and Invoice) to include the correct description and family of Products

In [41]:
notaFiscal = pd.merge(df, nomes, left_on = 'cod', right_on = 'cod')

In [45]:
notaFiscal.tail()

,cliente,NF,data,CNPJ,cidade,bairro,UF,cod,QTY,preco,descricao,Familia,unidade
160601,PORTAL DO EDEN COMERCIAL ALIM LTDA,7952,2018-02-03,07384953000140,RIO DE JANEIRO,IRAJA,RJ,050167,5,239.8,MOLHO P/ GRELHADOS 12X1.010L,Institucional,CX
160602,PORTAL DO EDEN COMERCIAL ALIM LTDA,7952,2018-02-03,07384953000140,RIO DE JANEIRO,IRAJA,RJ,050168,5,228.5,MOLHO DE ALHO C/ PIMENTA 12X1.010L,Institucional,CX
160603,PORTAL DO EDEN COMERCIAL ALIM LTDA,7952,2018-02-03,07384953000140,RIO DE JANEIRO,IRAJA,RJ,050169,5,228.5,MOLHO DE PIMENTA VERDE 12X1.010L,Institucional,CX
160604,PORTAL DO EDEN COMERCIAL ALIM LTDA,7952,2018-02-03,07384953000140,RIO DE JANEIRO,IRAJA,RJ,050170,5,228.5,MOLHO DE PIMENTA VULCÃO 12X1.010L,Institucional,CX
160605,PORTAL DO EDEN COMERCIAL ALIM LTDA,7952,2018-02-03,07384953000140,RIO DE JANEIRO,IRAJA,RJ,050171,5,228.5,MOLHO DE PIMENTA AMARELA 12X1.010L,Institucional,CX

#### Creates a New CSF file  with all the Correct Descriptions

In [46]:
notaFiscal.to_csv('C:/Mettricx/Projetos/SFoods/DataSet/NFe-SupraS.csv',encoding='utf-8', index=False)   # ,encoding='utf-8', index=False Grava CSV sem o Indice

In [47]:
df1 = pd.read_csv('C:/Mettricx/Projetos/SFoods/DataSet/NFe-SupraS.csv', dtype={'cod': object, 'NF': object, 'CNPJ': object})

In [48]:
df1.head()

,cliente,NF,data,CNPJ,cidade,bairro,UF,cod,QTY,preco,descricao,Familia,unidade
0,NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM ...,4,2014-08-29,27833615002018,RIO DE JANEIRO,CASIMIRO DE ABREU,RJ,020002,1,2.77,ALHO E CEBOLA PICADINHO S/SAL 180GR,Temperos,UN
1,TOP GREEN FRUIT HORTIFRUITGRANJEIROS LTDA,1275,2014-10-04,09642314000162,ARARUAMA,CENTRO,RJ,020002,24,66.48,ALHO E CEBOLA PICADINHO S/SAL 180GR,Temperos,UN
2,M L ZIELINSKI LANCHONETE E CONVENIENCIA,1285,2014-10-09,20815576000114,MACAE,SOL E MAR,RJ,020002,2,5.54,ALHO E CEBOLA PICADINHO S/SAL 180GR,Temperos,UN
3,NOVA ESPERANCA DE ARARUAMA LTDA EPP,1294,2014-10-14,05054332000172,ARARUAMA,MATARUNA,RJ,020002,18,49.86,ALHO E CEBOLA PICADINHO S/SAL 180GR,Temperos,UN
4,SUPERMERCADO SAO JUDAS TADEU LTDA,1296,2014-10-14,09653290000147,SAQUAREMA,BACAXA,RJ,020002,12,33.24,ALHO E CEBOLA PICADINHO S/SAL 180GR,Temperos,UN

#### Some invoices are issued but are not related to Product Sales. Therefore,will be deleted

In [49]:
df2 =  df1[(df1['Familia'] != 'Diversos') & 
           (df1['Familia'] != 'Manutenção de Ativo') & 
           (df1['Familia'] != 'Insumos') &
           (df1['Familia'] != 'Serviço')]

In [50]:
df2.tail()

,cliente,NF,data,CNPJ,cidade,bairro,UF,cod,QTY,preco,descricao,Familia,unidade
160601,PORTAL DO EDEN COMERCIAL ALIM LTDA,7952,2018-02-03,07384953000140,RIO DE JANEIRO,IRAJA,RJ,050167,5,239.8,MOLHO P/ GRELHADOS 12X1.010L,Institucional,CX
160602,PORTAL DO EDEN COMERCIAL ALIM LTDA,7952,2018-02-03,07384953000140,RIO DE JANEIRO,IRAJA,RJ,050168,5,228.5,MOLHO DE ALHO C/ PIMENTA 12X1.010L,Institucional,CX
160603,PORTAL DO EDEN COMERCIAL ALIM LTDA,7952,2018-02-03,07384953000140,RIO DE JANEIRO,IRAJA,RJ,050169,5,228.5,MOLHO DE PIMENTA VERDE 12X1.010L,Institucional,CX
160604,PORTAL DO EDEN COMERCIAL ALIM LTDA,7952,2018-02-03,07384953000140,RIO DE JANEIRO,IRAJA,RJ,050170,5,228.5,MOLHO DE PIMENTA VULCÃO 12X1.010L,Institucional,CX
160605,PORTAL DO EDEN COMERCIAL ALIM LTDA,7952,2018-02-03,07384953000140,RIO DE JANEIRO,IRAJA,RJ,050171,5,228.5,MOLHO DE PIMENTA AMARELA 12X1.010L,Institucional,CX